version: '3'

services:
  database:
    container_name: database
    restart: unless-stopped
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: simform_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '4306:3306'
    volumes:
      - dbdata:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./
      dockerfile: php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony_docker
    environment:
        APP_ENV: dev
        BASE_URL: 127.0.0.1  
    depends_on:
      - database 
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  encore:
        image: node:10-alpine
        volumes:
            - .:/var/www/symfony_docker
        ports:
            - "${DEV_SERVER_PORT:-8080}:8080"
        working_dir: /app
        command: ["yarn", "dev-server", "--host=0.0.0.0"]
volumes:
  dbdata:

       